language: java
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy --settings target/travis/settings.xml"
branches:
  except:
    - travis
env:
  global:
    - secure: "LQk7Ksh1P344Z52sx3/2vROBSWMIJO8W8NnebJSztQVD5Ey8x23PjZP/hnko+PKE5rH9nuxj8nEHWZsdcQ6ZyZnGpeOdV2byPrU1NOje5WWcU1Z8vF6Y+h7C0mxf0HKHWlCJyT8MTsO2cZiiCABSF9JXIEVw8HZ1XohEO3H/DH+ylMRLb3omZb7pp8C6x7wUgU+O+e95ee4YXrgSvauXNB9kaNamcqXPryORCEiD2lATDvGmp1SR0Y1zKXF9MocJ/9KYi9m/xvAIxHQoipt2hL4F3zSBIOuhZ4vJPjTs8SqBqiQm2hGlBonPnlNkWQvfkZHv7kWdF8bOUx5g3Jnn+feV7FoiV7+Onhepiecdmbv+Xf9uNxsvUlO+xXV2sW5TyK1YGpr2w3NijP3HFNopiLlZMgCzwpAf03s/rF7Uz51h2f9HjDz7/9KfKUQW1RXaV7uHkWJLdAt4gSb4ozePsU83tFg86fLVmTBpmrNDUd2SK84O4v4oGTrKhrjD2MIzeJHyYPkdNC3GMcju39aAldtcGo3pGWoutTuhqIHdx04G2G8CTXeS8najw0Y/H5RO6zqA+dhVIUQ4aqU4O1YhKl4NHxTbePLYeSJ8EVtXQfYZQo72GfmLCt/XQ1zc/TTOf1br+QhpXMF0rYq5wa2npA/fUY+PUrB3oeBGL9YKoQ0="
    - secure: "IuyOSo0XP8Fw5ZhOjs9qtp1uwQ5g9DH4JTavPbgvmoIE7J9GLrB5YwShDnmrw1sCAVsD4Y6j3eP/kAy7Jj6NdxaY5HrmprBpazkrgZLIKyA9ra2JF8n4UVbZv3g4TcZYuSJLkKgnVqsAsCukWXNmkJMgqHYpo3t2wz8AqRxvLg6cC+tnxDsmeuTZu6pVyp6hiJ2a9Li0taA0uwxpagkc59EWs4WNcG2wAPbPA2SD+vT5TBNJV1NEAlAqA64Ai/S/ViyYGA4hLaJ62g4kmfZla859b45HjcgQC2iT7aY1v8tWUd/wnaSBo1EReHVnWOjgglDGSr8554r4l7IhnQtujGQkvKp2Yk2TeLYUU9tX+MPSG9t/cw7FwkXVr8az0C4nBEt4SkE1ObEeviptQSUgzkIMJl6RQGtcKMFLIV9v4mL/QDpJSa9YLNp+EfEI+ikrghVPmJ3v+LMPrKFrNLgrvS47FuoTaq5mGdOaS4HVlQwGUAGGkpZ3w1kEWmA/KrbzyVZBz/aG8/ACewgoH8VTZXYGna4XKClSlTSPG10wJCj5dqGYrozvJtqRPyAyduoO09K6c9d4ggq1UQ2gQaPtsA1KuzrRRd/8RkxDi3F0TVgfSblEkzpRHYccB/aY7q0QmW5O608+5BWfDztEj0fhiJ0PZ5eUxrbS3jjkwCg10Mk="

branches:
  only:
    - master
    - /^release.*$/
